export default function PlayerMode() {
  return (
    <div>
      <div>player mode goes here...</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
      <div>v</div>
    </div>
  );
}
